### ISSUE TITLE
xOrDefault

### ISSUE THREAD

**Issue by electricessence** [OpenXmlDev/ts-oxpt#2] opened 2022-02-05 16:59 UTC
I love how your API is turning out.

I am still a bit concerned about making assumptions in your LinqIterableBase about what the defaults should be.   In respect to selecting 'nodes', `null` is obviously a valid default, but you (or I) might be better served providing an `.xOrNull()` method to be more explicit.

```ts
// TypeScript
textNodes.select(parseFloat).firstOrDefault() // if textNodes is empty, the value returned here is null.
```

```cs
// C#
textNodes.Select(double.Parse).FirstOrDefault() // if textNodes is empty, the value returned here is 0.
```

As I pointed out before, when calling an `.xOrDefault()`, if for some reason `T` is of type `number` you won't get `0` as the default as you would in C#.  And if you were attempting to filter by type: `typeof null == 'object'` where `typeof undefined == 'undefined'`.  So the behavior differs even though you are conforming to the .NET API.

Where I see having `null` as an acceptable default is whenever the expected type should be an object like a node.  It's just difficult to forsee how things might get weird if some amount of transformation is done by the consumer.

I'd also point to the weirdness in JS around `0` and `null`.  Really strange things can happen that simply won't happen in C#.
https://www.tutorialspoint.com/what-is-the-relation-between-null-and-0-in-javascript
https://blog.campvanilla.com/javascript-the-curious-case-of-null-0-7b131644e274?gi=bc5bbbc977f4

```ts
null > 0 || null == 0; // == false
undefined > 0 || undefined == 0; // == false
undefined >= 0 // == false
null >= 0; // == true WHAT!?
```

**Comment by electricessence** [comment] 2022-02-05 17:10
I think the important thing to keep in mind, is that in C#, the word "default" has a special meaning and expectation that simply can't apply to JavaScript.

**Comment by electricessence** [comment] 2022-02-05 18:06
Latest update includes `xOrNull` methods and eliminates hard `T` restrictions for `xOrDefault` methods.
https://github.com/tsdotnet/linq/releases/tag/v1.4.0

**Comment by ThomasBarnekow** [comment] 2022-02-05 21:42
Hi @electricessence, I did think about this very carefully. However, I knowingly and willingly decided to accept the slight difference in behavior between C# and TypeScript/JavaScript. Here are some considerations:

1. In LINQ to XML, you _almost always_ deal with reference types, where the default value is `null` and `xOrDefault()` is therefore expected to return `null`. "**Almost always**" in this case means that you had to remind me that `xOrDefault()` returns `0` for an empty `IEnumerable<int>`, for example. I had (almost completely) forgotten that it did that, likely because I almost never use such methods with value types ... mind you in the context of processing XML (such as Office Open XML), using either:
    - the strongly-typed classes (e.g., `Paragraph`, `Run`) provided by the [Open XML SDK](https://github.com/OfficeDev/Open-XML-SDK) or 
    - LINQ to XML (e.g., using the `XElement` class with `XName` instances corresponding to `Paragraph` or `Run`).
2. Forcing developers to use a different API just because of a difference between the return values of the C# vs. TypeScript counterparts in rare cases (effectively just the `number` type) did not feel right. Unless you are using .NET 6, to provide an explicit default value in C#, you would use the `.DefaultIfEmpty()` extension method, the counterpart of which is also offered in my API. Therefore, in those rare cases in which you deal with sequences of numbers (in LINQ to XML) and expect the return value of `xOrDefault()` to be `0` or some other numeric value (but not `null`), developers can use the `defaultIfEmpty()` method.
3. .NET 6 added further overloads to the `xOrDefault()` methods, including one that lets you provide just a default value and another one that lets you provide a predicate and a default value, in that order. I will consider adding those in a future release.
4. There are other LINQ-related implementations out there (see [mihaifm/linq](https://github.com/mihaifm/linq), for example) that also return either `null` or `undefined`. For the `xOrDefault()` methods, [mihaifm/linq](https://github.com/mihaifm/linq) offers an optional default value as a second parameter (after the predicate): `firstOrDefault(predicate?: (element: T, index: number) => boolean, defaultValue?: T): T | undefined;`. 

Structurally, my API is in sync with .NET 5 and earlier. The APIs offered by .NET 6 can be added later. The minor behavioral difference regarding the default value for essentially just the `number` type is acceptable in the LINQ to XML context.

**Comment by ThomasBarnekow** [comment] 2022-02-05 21:52
> Latest update includes `xOrNull` methods and eliminates hard `T` restrictions for `xOrDefault` methods. https://github.com/tsdotnet/linq/releases/tag/v1.4.0

I've not tested this, but would it be possible to do the following?

```typescript
const emptyNumericSequence = linqExtended<number>([]);
const value = emptyNumericSequence.firstOrDefault('foo');
```

Since `'foo'` is a `string`, the type of `value` would be `number | string`, matching your signature:

```typescript
firstOrDefault<TDefault>(defaultValue: TDefault, predicate?: PredicateWithIndex<T>): T | TDefault;
```

If so, this would be weird. However, I have not seen any constraints that would prevent me from passing arbitrary default values.

**Comment by ThomasBarnekow** [comment] 2022-02-05 22:14
> I'd also point to the weirdness in JS around `0` and `null`. Really strange things can happen that simply won't happen in C#. https://www.tutorialspoint.com/what-is-the-relation-between-null-and-0-in-javascript https://blog.campvanilla.com/javascript-the-curious-case-of-null-0-7b131644e274?gi=bc5bbbc977f4
> 
> ```ts
> null > 0 || null == 0; // == false
> undefined > 0 || undefined == 0; // == false
> undefined >= 0 // == false
> null >= 0; // == true WHAT!?
> ```

I never said JS isn't weird, which is why I never developed in JS but only TypeScript. In TypeScript, some of your above expressions would not even compile.

To check, I created a quick unit test:

```typescript
test('weird stuff', () => {
  expect(null === true).toBe(false);
  expect(null == false).toBe(false);
  expect(null! > 0).toBe(false);
  expect(null! == 0).toBe(false);
  expect(null! >= 0).toBe(true);

  expect(undefined === true).toBe(false);
  expect(undefined == false).toBe(false);
  expect(undefined! > 0).toBe(false);
  expect(undefined == 0).toBe(false);
  expect(undefined! >= 0).toBe(false);
});
```

The fact that `expect(null! >= 0).toBe(true);` passes explains my hesitation to use JS. At least in TypeScript, `null >= 0` (without the non-null assertion operator `!`) does not compile. Obviously, `null! >= 0` may produce nonsense. 

One thing that is consistent, though, is that `undefined`, `null`, `0`, and `false` (and `''`) are all falsy. You could make use of that fact, for example.

**Comment by electricessence** [comment] 2022-02-06 04:57
https://github.com/OpenXmlDev/linq-to-xml/issues/2#issuecomment-1030703792
In respect to this.  Holding on too tightly to parity with .NET can bite you in the end.  Different languages, different environments, different norms, different coding standards.   Just my take as I went from conforming tightly to .NET to looking for ways to be more conforming to JS uses.

C# has features that JS doesn't and may never have.  Complex overloading _is_ possible in JS, but not easy, error prone, and can be confusing to the consumer.  So best practice tends to be to "keep it simple".

I say again: the term 'default' has special meaning in C#.  It is not implemented in JS/TS.

**Comment by electricessence** [comment] 2022-02-06 05:00
Side note: I'm totally okay with whatever decision you make.  I'm just providing an alternative view and looking for insight myself.

**Comment by electricessence** [comment] 2022-02-06 05:08
https://github.com/OpenXmlDev/linq-to-xml/issues/2#issuecomment-1030705164
`'foo'` is now allowed.  This of course wouldn't be possible in C# with just `T`, but the point of TS is not to create an API that prevents you from doing things, but to provide type guidance (or type flow) for your code.  Without any typing, a JavaScript consumer (latest version or otherwise) could have done exactly that and it would have worked.

Since that is factually true for JavaScript, it is more important to ensure that the type definition correctly reflects its behavior.

Consider:
```ts
const emptyNumericSequence = linqExtended<number>([]);
const value = emptyNumericSequence.firstOrDefault(null); // number | null
```
^ This may actually be desired behavior.  But with the previous typing, this would not be possible unless `T` of the numeric sequence was typed as `number | null`.

**Comment by electricessence** [comment] 2022-02-06 05:14
> I never said JS isn't weird, which is why I never developed in JS but only TypeScript. In TypeScript, some of your above expressions would not even compile.

Depends on your tsconfig, but yes, you can make it compile and proves even more so how troublesome these kinds of evaluations can be:
https://www.typescriptlang.org/play/?ssl=7&ssc=29&pln=1&pc=1#code/MYewdgzgLgBAcgVQDJJgLhgQzATxgXhjAFcAbUgbgChRJYA1AeQEkARABnS1wJmLAAmAUwBmASzBCB1KohQwAfDE4AfFfGSp8hdhRgB6fQUIjMpCEKpM2nJavXWOx5XsPPT5y49s6DR7TAeFrKaijqu-oRQAE7EQjAA6gASAIIAKgCEAPxAA
```ts
const NULL : any = null;
const VOID0 : any = undefined;

NULL > 0 || NULL == 0; // == false
VOID0 > 0 || VOID0 == 0; // == false
VOID0 >= 0 // == false
NULL >= 0; // == true WHAT!?
```

**Comment by electricessence** [comment] 2022-02-06 05:16
> One thing that is consistent, though, is that `undefined`, `null`, `0`, and `false` (and `''`) are all falsy. You could make use of that fact, for example.

Yes.  In some cases, that can make things a bit easier.  But people need to know what they are doing and what side-effects it can cause.

**Comment by electricessence** [comment] 2022-02-06 05:23
> The fact that expect(null! >= 0).toBe(true); passes explains my hesitation to use JS. At least in TypeScript, null >= 0 (without the non-null assertion operator !) does not compile. Obviously, null! >= 0 may produce nonsense.

TS is awesome.  But, ultimately it _IS_ JavaScript.  It's a superset.  You can't separate JS from TS, but you can separate TS from JS.
I would hate to write in pure JS again, but if you're gonna be in a JS world (which TS is) you have to embrace it.  For example, conforming to standards like camelCasing instead of TitleCasing.  JavaScript devs wouldn't want to use a JS lib that used TitleCasing because it would get weird.

What you might not be getting with `null >= 0` is that when negative side-effects occur, it won't be because someone wrote that explicitly.  It will occur like this:
```ts
// assume that sequencehas a null value in it.  And that the following is your LinqIterable.
sequence.firstOrDefault(n => n >= 0);
```
Sure, this isn't likely to happen but I'm just pointing out that because JS has these strange effects, including the horrific introduction of `null` and `undefined`, (as I said before) holding on too tightly to parity may bite you in the future.

**Comment by ThomasBarnekow** [comment] 2022-02-06 19:10
Hi @electricessence, this discussion inspired me to make a change to the API, which is already published as `v0.9.0` on [npmjs.com](https://www.npmjs.com/package/@openxmldev/linq-to-xml).

Both the [README](https://github.com/OpenXmlDev/linq-to-xml#default-values) in this repo and the main page on [npmjs.com](https://www.npmjs.com/package/@openxmldev/linq-to-xml) talk about the language-specific differences between C# and TypeScript/JavaScript and in particular the differences between the default values used for non-nullable value types.

Based on the argumentation (which I am not repeating here), the API now looks like this for `firstOrDefault()`, `lastOrDefault()`, and `singleOrDefault()`:

```typescript
xOrDefault(): T | undefined;
xOrDefault(predicate: PredicateWithIndex<T>): T | undefined;
xOrDefault(defaultValue: T): T;
xOrDefault(predicate: PredicateWithIndex<T>, defaultValue: T): T;
```

The essential parts of the change are:
- the additional overloads taking a default value and 
- the fact that the API no longer returns `null` but `undefined`.

The above API is 100% consistent with the corresponding API in .NET 6 (using `T` instead of `TSource` below):

```csharp
public static T? FirstOrDefault<T>(this IEnumerable<T> source);
public static T? FirstOrDefault<T>(this IEnumerable<T> source, Func<T, bool> predicate);
public static T  FirstOrDefault<T>(this IEnumerable<T> source, T defaultValue);
public static T  FirstOrDefault<T>(this IEnumerable<T> source, Func<T, bool> predicate, T defaultValue);
```

One could still construct "interesting" edge cases such as sequences of "predicates" of type `PredicateWithIndex<T>` where you will not be able to distinguish between an actual predicate and a default value. However, those cases are really irrelevant for LINQ to XML, where you never deal with sequences of functions. Therefore, at run-time, the implementation treats any function as a predicate.

**Comment by electricessence** [comment] 2022-02-06 20:03
```ts
xOrDefault(): T | undefined;
xOrDefault(predicate: PredicateWithIndex<T>): T | undefined;
xOrDefault(defaultValue: T): T;
xOrDefault(predicate: PredicateWithIndex<T>, defaultValue: T): T;
```

There is a reason that I explained before why _I DO NOT DO THIS_ overloading.

You will be unable to differentiate between a default value of a delegate.
TS overloads are fake.  They don't do anything other than define the potential type flow.  Even so, this type of overloading is typically not done with delegates or tasks in .NET as it can create an API that is problematic.

Here's where it will break (if this is even a possible use case with your lib):
```ts
delegateSequence = linq<Func<int, bool>>(delegates);
delegate = delegateSequence.firstOrDefault(e=> e!=0 /* handle default case? */);
```

What do you see above that could go wrong?
Well the consumer might be trying to provide a default delegate, but instead end up with a where clause that is validating `e` which will never return any results even if there are some and only return the default delegate provided.

Hence why this is not a possible overload combination in .NET LINQ, but part of that is that there no need to because C# actually returns the default type as expected.

**Comment by electricessence** [comment] 2022-02-06 20:07
The API choices I've made with tsdotnet/linq have a lot to do with already grinding through these kinds of API conundrums.

Hence why the primary signature of `xOrDefault` methods is:
```ts
singleOrDefault<T, TDefault>(defaultValue?:TDefault, predicate?:PredicateWithIndex<T>)
     : T | TDefault | undefined { }
```
Because there is no question about what is what here.  defaultValue must be provided before the predicate.  And if that is not what is desired, then a separate method signature (singleOrUndefined, or singleOrNull) is provided.

**Comment by ThomasBarnekow** [comment] 2022-02-06 22:18
> You will be unable to differentiate between a default value of a delegate. TS overloads are fake. They don't do anything other than define the potential type flow. Even so, this type of overloading is typically not done with delegates or tasks in .NET as it can create an API that is problematic.
> 
> Here's where it will break (if this is even a possible use case with your lib):
> 
> ```ts
> delegateSequence = linq<Func<int, bool>>(delegates);
> delegate = delegateSequence.firstOrDefault(e=> e!=0 /* handle default case? */);
> ```

Since you made that point earlier, I am fully aware of this, which is why I added the following concluding remark in [my comment above](https://github.com/OpenXmlDev/linq-to-xml/issues/2#issuecomment-1030894675)

> One could still construct "interesting" edge cases such as sequences of "predicates" of type PredicateWithIndex<T> where you will not be able to distinguish between an actual predicate and a default value. However, those cases are really irrelevant for LINQ to XML, where you never deal with sequences of functions. Therefore, at run-time, the implementation treats any function as a predicate.

In your response, you have done exactly that again, i.e., you have constructed an "interesting" edge case. However, your parenthetical is important: "if this is even a possible use case with your lib". To be very clear: That use case is of no practical relevance whatsoever. In LINQ to XML, we are not looking at sequences of functions. I would also guess that in LINQ (i.e., in a wider range of use cases), sequences of functions are an edge case. In the extreme case, we are talking about a case that is of purely theoretical interest.

Thus, weighing the purely theoretical nature of the above use case (at least for LINQ to XML) against more relevant factors such as consistency with the corresponding .NET APIs, I decided to be consistent with .NET 6. This makes it very easy for developers to consume those APIs.

In case anybody wanted to use sequences of functions, default values can be defined in the following two ways:

```typescript
const sequence = linqIterable<PredicateWithIndex<number>>([]);
const defaultValue: PredicateWithIndex<number> = () => false;

// First option: use defaultIfEmpty() function.
const element1 = sequence.defaultIfEmpty(defaultValue).firstOrDefault();

// Second option: use firstOrDefault(predicate, defaultValue) overload.
const element2 = sequence.firstOrDefault(() => true, defaultValue);
```

The first option corresponds to what you would have to do prior to .NET 6. The second option leverages the overload that corresponds to one that was added in .NET 6. In this rare or even non-existent edge case, you would have to pass a predicate `() => true` that would not normally be required. This is not the best developer experience. However, this is a much better API design compromise than offering an API for the typical case where such API would not be regarded as "natural" by developers.

Let me illustrate that developer experience also with another simple example. Let's look at the `ArgumentException` class, which you also provide in your @tsdotnet/exceptions package.

In .NET, an `ArgumentException` instance can be constructed with the following overloads:

```csharp
public ArgumentException();
public ArgumentException(string? message);
public ArgumentException(string? message, Exception? innerException);
public ArgumentException(string? message, string? paramName);
public ArgumentException(string? message, string? paramName, Exception? innerException);
```

In your package, an `ArgumentException` can be constructed with a single constructor:

```typescript
constructor(paramName: string, message?: string, innerException?: unknown);
```

While it is possible to provide all parameters that the .NET counterpart supports, the arguments are in a different order, i.e., `paramName` and `message` are swapped. This can be a gotcha if you are used to the order of arguments in .NET. Secondly, the API does not allow `undefined` for `paramName`, which is an explicit use case in .NET. For example, I wanted to throw exceptions that are similar to what is thrown in LINQ to XML in .NET. Guess what, you will often enough come across something 
like `new ArgumentException(someMessage)`. While you can write something like `throw new ArgumentException('', someMessage)` in your API, it does not feel natural.

**Comment by ThomasBarnekow** [comment] 2022-02-07 00:24
@electricessence, I just thought about one more thing.

Using `singleOrDefault()` as an example, the set of overloads that is most similar to their .NET 6 counterparts is this:

```typescript
singleOrDefault(): T | undefined;
singleOrDefault(predicate: PredicateWithIndex<T>): T | undefined;
singleOrDefault(defaultValue: T): T;
singleOrDefault(predicate: PredicateWithIndex<T>, defaultValue: T): T;
```

The first two overloads existed prior to .NET 6 while the last two were added in .NET 6.

If sequences of functions were a thing, removing the `singleOrDefault(defaultValue: T): T` overload would remove any ambiguity as well. The set of overloads would then be this:

```typescript
singleOrDefault(): T | undefined;
singleOrDefault(predicate: PredicateWithIndex<T>): T | undefined;
singleOrDefault(predicate: PredicateWithIndex<T>, defaultValue: T): T;
```

This is as unambiguous as your API while being consistent with the .NET API. Would you agree?

**Comment by electricessence** [comment] 2022-02-07 03:58
So here's the last couple things to consider:

If you write an overload that has a `T` as a first param, and another overload as `PredicateWithIndex<T>` as a first param.  Then for every call, you have do a type check in JS to see if what is being passed is a `Function`.

But the in lies the trouble.  Unless you can guarantee that the underlying iterable does not contain functions as its content, then you'll never be sure if you've misinterpreted what the consumer wanted.  Again, because ultimately, this is JS and not C#.

To your point above about `ArgumentException`.  Because this is a JavaScript environment, _I avoid at all costs_ implementing special overload logic as it tends to make the code more likely to have bugs and testing is more complicated and troublesome.  So instead of fighting with parity in .NET, I normalize the parameters and stick with them.  If necessary, creating different methods solves these overload problems.  And in rare cases, where it clearly has a high value and if a type check/switch can ensure a proper code path, then I _might_ implement special overloading.

I understand the desire to keep with parity, but as I mentioned, I lost that battle a long time ago, and found a balance that favored JS.  If you follow my API and make `xOrDefault` always have a `defaultValue` (it can't be omitted) as its first param, then there's no question about what it does.  Again, 'default' is a special word.  That has questionable meaning in JS.  So for me, I realized that it made more sense to be sure the consumer also understands what they need to do when using that method.  It provides more functionality, while being sure it does what it says.  Meanwhile, really think what you're trying to emulate is the `xOrNull` or `xOrUndefined` methods.  Which are totally fine because there is no question about the result and no need to provide a value.
I kind of like the new `xOrNull` methods because they're more brief.

**Comment by electricessence** [comment] 2022-02-07 04:01
Just gotta say:  I'm 100% supportive of your decisions.  I appreciate that you are clearly informed and like me have  a desire to figure out what's best.  I'm confident from our discussions that you get these challenges and for me, I see that some of these concepts may be trivial to your API.  In the end, I like to be sure you're going forward knowing what challenges you might face.

**Comment by electricessence** [comment] 2022-02-07 04:07
```ts
singleOrDefault(): T | undefined;
singleOrDefault(predicate: PredicateWithIndex<T>): T | undefined;
singleOrDefault(predicate: PredicateWithIndex<T>, defaultValue: T): T;
```

But what if i want to provide a default value and no predicate?
Again, it's the `Default` in `xOrDefault` that you're wrestling with.
As it has been true in the past for JS.  JS never had type flow overloads.   Sure, runtime overloading is possible, but causes you to write more code.

**Comment by electricessence** [comment] 2022-02-07 04:07
To my earlier point, consider this for C#:
Why does everything have a `MethodName<T>(T value)` and subsequent `MethodNameAsync<T>(Task<T> task)` version?
Why not just `MethodName<T>(Task<T> value)`?
Maybe the answer isn't so obvious.  But it quickly becomes obvious once you start passing tasks around that you don't want being treated as `T`.

**Comment by electricessence** [comment] 2022-02-07 04:10
Getting late here.  But I'm excited for how this project is going.

**Comment by ThomasBarnekow** [comment] 2022-02-07 09:51
@electricessence, thanks for your latest answers.

> To your point above about ArgumentException. Because this is a JavaScript environment, I avoid at all costs implementing special overload logic as it tends to make the code more likely to have bugs and testing is more complicated and troublesome. 

My point is not about the single constructor or the absence of overloads. My point is about the "wrong" order of the arguments compared to the .NET counterpart. I believe you could have used the same order as in .NET, which would have been a good thing for a package scoped `@tsdotnet`. Developers will be surprised by this different order.

> Again, it's the Default in xOrDefault that you're wrestling with.

I can confirm that I am _not_ wrestling with the "Default". If you looked a the [README](https://github.com/OpenXmlDev/linq-to-xml#default-values), where I describe the language-specific differences regarding default values, I said the following:

> On an abstract level, the C# and TypeScript counterparts _behave in the same way_. For empty sequences, they _both return the respective default values_. Let that sink in for a moment.
>
> On a concrete level, however, the language-specific difference between the default values for non-nullable value types in C# (e.g., int, bool) and the corresponding types in TypeScript (e.g., number, boolean) is that:
> - in C#, the default values are 0 and false, respectively; and
> - in TypeScript, the default value is undefined in all cases.

I am _embracing_ the fact that the default value in TypeScript is `undefined` in all cases. I even think that this behavior has _advantages_. Lastly, the behavior is well-documented in the API documentation. The only remark that I will likely add in a next release is that the overload taking just a default value should not be used for the edge case of sequences of functions.

> Why does everything have a `MethodName<T>(T value)` and subsequent `MethodNameAsync<T>(Task<T> task)` version?
> Why not just `MethodName<T>(Task<T> value)`?

I think what you mean are methods returning a `T` in the synchronous case and a `Task<T>` in the asynchronous case. Right? Firstly, the `Async` postfix is a naming convention that is just "helpful" because it signals that you'd have to `await` the results, for example. Secondly, consider the following synchronous method: 

```csharp
T MethodName(string value);
```

You cannot have an overload with the same name that only differs in its return type. Therefore, the corresponding asynchronous method looks like this by convention (ignoring further typical overloads adding a `CancellationToken`, for example):

```csharp
Task<T> MethodNameAsync(string value);
```

You could use any other method name that does not clash with `MethodName`. Using `Async` as a postfix in such cases just makes a lot of sense.

I think we can close this issue now. I do appreciate the discussion, which also helped me amend and confirm the design of my API (because you made me think hard about some things such as default values).

**Comment by electricessence** [comment] 2022-02-07 14:39
> My point is not about the single constructor or the absence of overloads. My point is about the "wrong" order of the arguments compared to the .NET counterpart. I believe you could have used the same order as in .NET, which would have been a good thing for a package scoped `@tsdotnet`. Developers will be surprised by this different order.

Well, that's a very interesting point indeed.  In .NET `ArgumentException` deviates from its sub-classes in that typically you provide the `paramName` first.  IMO, for years, I've always thought this was a very confusing choice as any `ArgumentExeception` you typically want to know which one.  I would quite often get confused and have these reversed as they are both strings.  So for consistency, I made tsdotnet's version of `ArgumentException` behave like it's sub classes. `ArgumentNullException` for example.

**Comment by electricessence** [comment] 2022-02-07 14:53
> I am embracing the fact that the default value in TypeScript is undefined in all cases.

I think you're doing a great job and as the alternative to providing a defaultValue is that the consumer can easily do the following:
```ts
numericSequence.firstOrDefault() ?? 0
// or
numericSequence.firstOrDefault() || 0
```
But if I had to chose, I would definitely not have divergent signatures.

**Comment by electricessence** [comment] 2022-02-07 15:11
> I think what you mean are methods returning a `T`

No.  What you are referring to is the obvious.  There are enough use cases where you pass a `Task<T>` or `ValueTask<T>` as a parameter instead of `T`, especially in extension libraries, but the way to ensure type flow doesn't break because you might actually want to pass `Task<T>` to your synchronous version is to append `Async` to the method name.
I've even encountered an issue where type inference in C# won't work with `async ()=> {}` when you provide overloads for both `ValueTask` and `Task` and have to differentiate by using a different name for the `Task` version because you want the default to be `ValueTask`.

**Closed as completed** 2022-02-07 15:48 UTC
