### ISSUE TITLE
Some classes are already prepared for you.

### ISSUE THREAD

**Issue by electricessence** [OpenXmlDev/ts-oxpt#1] opened 2022-01-28 11:49 UTC
This looks like an interesting project.

Just a note, tsdotnet already has classes that seem to fit some of your use cases:

### StringBuilder
https://github.com/tsdotnet/string-builder

### LinqIterable
https://github.com/tsdotnet/linq/blob/master/src/linqExtended.ts
You might try inheriting from `LinqExtended<T>` instead of writing your own.

**Comment by ThomasBarnekow** [comment] 2022-01-28 12:18
Hi @electricessence, thanks for your message. And thanks a lot for the @tsdotnet packages, which are great.

I did not see the `StringBuilder` and will have a look. I only needed a super-simple, internal utility and mine does the job without requiring any dependency. So I just wrote it myself. I did not even mean to implement anything with more functionality.

I did consider inheriting from `LinqExtended<T>` but then decided against it. Inheriting would have meant that I'd not have to implement `count`, `any`, `all`, and `toArray` (four very simple methods). However, I would have had to override the other eight methods anyhow.

But now that we are talking, I am of course very open to reconsidering this. So, from your point of view, what would be the advantages of inheriting from `LinqExtended<T>` (given that I already have a full implementation with 100% test coverage)? For example, would that mean better compatibility for users of @tsdotnet/linq?

**Comment by electricessence** [comment] 2022-01-28 16:02
With respect to `LinqExtended<T>`, you are correct, you may need to override certain methods, but IMO, overall, your file could have less references and just be lighter.
The `Linq<T>` and `LinqExtended<T>` (extends `Linq<T>`) classes are simply utilities for offering very common operations.

When I read your code, I don't see what exactly you are doing different in `LinqIterable<T>`.
Can you look at `LinqExtended<T>` and compare it and tell me what you are trying to do different?
What might your overrides be trying to do?
I think you should try extending from it.

**Comment by electricessence** [comment] 2022-01-28 16:04
A side note.  I was at one point going to implement the System.Xml.Linq namespace from .NET.
It would be interesting to be able to offer this in a way that works well and follows that API.
Maybe you're close?  Maybe your finished?  Very cool. 

Of course it would be it's on NPM package that imported /linq and extended it.   Probably just as you are doing.

**Comment by ThomasBarnekow** [comment] 2022-01-28 17:03
Let me comment on your most recent note first.

> A side note. I was at one point going to implement the System.Xml.Linq namespace from .NET. It would be interesting to be able to offer this in a way that works well and follows that API. Maybe you're close? Maybe your finished? Very cool.

When looking at your repositories, I saw that you wanted to do that at one point. I also messaged you to ask whether you were still planning to finish that work. Since I needed it urgently, I then decided to implement it myself. And, yes, it follows the LINQ to XML API very closely. From my point of view, I am indeed done. Being a heavy user of LINQ to XML myself, I only left out those parts that I have never used in the past six years or so.

> Of course it would be it's on NPM package that imported /linq and extended it. Probably just as you are doing.

That is exactly what I am doing. I am going to publish this relatively soon.

**Comment by electricessence** [comment] 2022-01-28 17:18
Well this is great.  Love seeing my linq lib being used as it's supposed to.
My final point for extending from LinqExtended is simply to reduce your total package size.

**Comment by electricessence** [comment] 2022-01-28 17:22
If and when you decide to isolate to it's own NPM package, I'd be happy to contribute or at least help with code reviews.

**Comment by ThomasBarnekow** [comment] 2022-01-28 18:48
> When I read your code, I don't see what exactly you are doing different in `LinqIterable<T>`. Can you look at `LinqExtended<T>` and compare it and tell me what you are trying to do different? What might your overrides be trying to do? I think you should try extending from it.

Much like you created `LinqExtended<T>` to provide extended functionality, I needed a class to provide methods beyond those provided by `LinqExtended<T>`:

- `first(predicate?: PredicateWithIndex<T>): T`
- `firstOrDefault(predicate?: PredicateWithIndex<T>): T | null`
- `last(predicate?: PredicateWithIndex<T>): T`
- `lastOrDefault(predicate?: PredicateWithIndex<T>): T | null`
- `single(predicate?: PredicateWithIndex<T>): T`
- `singleOrDefault(predicate?: PredicateWithIndex<T>): T | null`
- `selectMany<TResult>(selector: SelectorWithIndex<T, Iterable<TResult>>): LinqIterable<TResult>`

To support frequent code patterns like `sequence.select((e) => e.property).first()`, I needed to override the following methods:

- `select<TResult> (selector: SelectorWithIndex<T, TResult>): LinqExtended<TResult>`
- `groupBy<TKey> (keySelector: SelectorWithIndex<T, TKey>): LinqExtended<LinqGrouping<TKey, T>>`

I've not yet overridden

- `where (predicate: PredicateWithIndex<T>): LinqExtended<T>`

in `LinqIterable<T>` because that method is overridden by the subclasses of `LinqIterable<T>`, instances of which are returned by classes like `XElement` and `XContainer`. Thus, my uses cases are covered by those subclasses. Should I find a gap, I can always add the method later on.

I then thought that the following methods implemented by `LinqExtended<T>` provided a useful extension mechanism:

- `filter (...filters: IterableFilter<T>[]): LinqExtended<T>`
- `filters (filters: Iterable<IterableFilter<T>>): LinqExtended<T>`
- `transform<TResult> (transform: IterableValueTransform<T, TResult>): LinqExtended<TResult>`

Obviously, I needed to override them in support of a pattern like `sequence.filter(someCustomFilter).first()`.

I did not want to offer the following method, because it is actually not a filter and identical to the `transform` method above (as stated in the method's documentation): 

- `filter<TResult> (filter: IterableValueTransform<T, TResult>): LinqExtended<TResult>`

Thus, I would have had to override a method that I did not want to offer in my API. Maybe you can explain to me why this method exists.

The following four methods are the only ones that I can "just inherit" from `LinqExtended<T>`:

- `count (predicate?: PredicateWithIndex<T>): number`
- `any (predicate?: PredicateWithIndex<T>): boolean`´
- `all (predicate: PredicateWithIndex<T>): boolean`
- `toArray (): T[]`

Thus, the cost-benefit analysis of inheriting from `LinqExtended<T>` vs. having my own root class was this:

- Inherit from `LinqExtended<T>`
  - _Benefit_: Inherit four methods that I don't have to implement and unit-test
  - _Cost_: Inherit one method that I don't want and take an additional dependency on an existing class hierarchy in which I have to override five to six methods anyhow
- Have my own root class
  - _Benefit_: Do not take a dependency and inherit a method that I do not want
  - _Cost_: Implement and unit-test four one-liners

Looking at those four one-liners, which are in turn implemented using functions from @tsdotnet/linq, what would I save by inheriting from `LinqExtended<T>`?

In my mind, a solution could be to enhance `LinqExtended<T>` even further by adding the methods (e.g., `first`) that I added to `LinqIterable<T>`. In that case, I could simply inherit from `LinqExtended<T>` and only provide the classes that currently inherit from `LinqIterable<T>`.

**Comment by electricessence** [comment] 2022-01-28 19:28
I think the value comes from that you're not only extending from `LinkeExtended<T>` but also from `Linq<T>` and you get all that base functionality.  This was partially the intention to demonstrate how it can be done.

The other methods you had to add seem trivial.
So what you're suggesting is that the cost was that you would have functionality that you didn't need.
That's totally fair!  I'm happy to see you making this decision.  It's exactly the reason I wanted tsdotnet/linq to be so modular so that it was not necessary to incur the cost of importing everything and that you could only get what you needed.  I don't know how familiar you were with previous iterations but before it was all or nothing, and all was **too much**.

As you probably already realize, `Linq<T>` and `LinqExtended<T>` are not necessary to use the lib, there just there as shortcuts for setting up enumerables/iterables.  I can see that you've implemented your own transforms (`IterableValueTransform<T>`) exactly as I hoped others would.  This makes me very happy. :)

> In my mind, a solution could be to enhance LinqExtended<T> even further by adding the methods (e.g., first) that I added to LinqIterable<T>. In that case, I could simply inherit from LinqExtended<T> and only provide the classes that currently inherit from LinqIterable<T>.

... I didn't want to make too many assumptions about what people would use as using a resolution is as simple as:
```ts
myLinqExt.resolve(first); // a very JavaScripty thing to do
```

Adding all the functionality might end up simply being bloat.
That said, some might like a class called `LinqDotNet<T>` that has all the methods and properly exposes that throughout the chain.  But if used, would incur the entire cost of the lib which is quite a bit.

Again, I just didn't feel it was my call to add too many options when it was trivial to call `.resolve` or `.filter`.

Another thing to throw in there is that in JS/TS you can do things that C# can't, and it might be more preferred this way:
```ts
e = myLinqExt.first();
e = myLinqExt.first.orDefault();
```
So you could write a class that uses the resolution, or it's alternate to provide 'stubs' for `.first` `.single` and `.last` but then are reusing that class to provide only 3 new methods/properties on `LinqExtended<T>`.

**Comment by electricessence** [comment] 2022-01-28 19:32
I'm a bit inspired by this, I might make an update today.

**Comment by ThomasBarnekow** [comment] 2022-01-28 20:14
Thanks for the discussion! This is very helpful. And you might have seen that I was quite a bit inspired by your library!

> I think the value comes from that you're not only extending from LinkeExtended<T> but also from Linq<T> and you get all that base functionality. This was partially the intention to demonstrate how it can be done.

I did look at the `Linq<T>` and `LinqExtended<T>` classes and used them as a pattern. However, what I noted is that `LinqExtended<T>` overloaded four methods (`filter`, `filters`, `transform`) from `Linq<T>` and only kept the constructor, `[Symbol.iterator]`, and `resolve`. I did implement those in `LinqIterable<T>` as well.

> I can see that you've implemented your own transforms (IterableValueTransform<T>) exactly as I hoped others would. This makes me very happy. :)

I liked this functional programming pattern and thought it would be best to implement the C# extension methods provided by the `Extensions.cs` class in LINQ to XML in this way. This way, `LinqIterable<T>` and its subclasses are mere wrappers provided for convenience, i.e., the ability to use LINQ to XML in TypeScript as you would in C#. 

In TypeScript, the `filter`, `transform`, and `resolve` methods would be totally sufficient to use the LINQ-to-XML-specific transformations. For example, the following statement is the most natural way for C# developers using LINQ to XML today to get the `w:val` attributes of all descendants of a given element (where `W` is a class having a static `val` property of type `XName`):

```typescript
const sequence = element
    .descendants()
    .attributes(W.val);
```

Using the generic `transform` method that you also implement in both `Linq<T>` and `LinqExtended<T>`, this can also be written as follows:

```typescript
const sequence = element
    .descendants()
    .transform(attributes(W.val));
```

However, this is not how people are used to write their code. But, it serves us very well as an extension mechanism and, thus, provides for a lot of flexibility. While I also provided the wrappers for convenience, I felt it was very useful to also provide those more generic methods, which don't exist in the C# version.

> If and when you decide to isolate to it's own NPM package, I'd be happy to contribute or at least help with code reviews.

I was actually planning to use this nx-based monorepo (`ts-oxpt`) to host several related NPM packages, with `linq-to-xml` being the first one to be published. Are you saying that this is not a good idea? I am always open to suggestions regarding best practices.

**Comment by electricessence** [comment] 2022-01-28 21:31
So I'm trying to make an update and publish it to NPM but it's giving me grief.
I haven't published in a while.  The code is in the master branch if you wanna see the update.
I added `.selectMany()` `.first()` `.firstOrDefault(value)` `.last()` `.lastOrDefault(value)` `.skip(count)` and `.take(count)`.

**Comment by electricessence** [comment] 2022-01-29 01:27
OK!  New release!

https://www.npmjs.com/package/@tsdotnet/linq
https://github.com/tsdotnet/linq/releases/tag/v1.1.0

Should solve most of your issues.
I didn't include `.single()` or `.singleOrDefault()` because in .NET world they're not as favored as `.first()` and  `.firstOrDefault(value)` and can be confusing as you'll throw if there's more than one.
A added skip, and take, as they can get the same result as `elementAt()` and `elementAt` isn't used that commonly.

Please do me the honor and the favor of attempting to use this new `LinqExtended<T>` as the repo has been fully updated and refreshed.

**Comment by electricessence** [comment] 2022-01-29 01:49
> I was actually planning to use this nx-based monorepo (ts-oxpt) to host several related NPM packages, with linq-to-xml being the first one to be published. Are you saying that this is not a good idea? I am always open to suggestions regarding best practices.

I'm not a fan of mono-repos when dealing with utilities/components.
Keep it granular IMO.

Looking at your use case for a `XmlLinq.cs` I can see how you might need to override the entire class to ensure it emits the same type.  This is a challenge to make easy, but it might be able to be done through some sort of factory that generates the class with a base type that you expect to emit.  It will take me some brain power to get it right, but it might be possible in an updated version.

**Comment by ThomasBarnekow** [comment] 2022-01-29 09:49
I thought about this repository, which is currently called `ts-oxpt`, which means _Open XML PowerTools for TypeScript_. As the PowerTools are very much geared towards Open XML while LINQ to XML is broader, I decided to focus this repository on just LINQ to XML and possibly tightly related things such as examples.

Your extending `LinqExtended<T>` further is much appreciated. However, the selection of methods such as `single()` and `singleOrDefault()` is based on the typical use cases that I have and see. Therefore, if some of the frequently-used methods are missing, I might still have to create my own class and override "enough" methods. I'm thinking about a solution that I will share with you if it works.

**Comment by ThomasBarnekow** [comment] 2022-01-29 14:22
@electricessence, I have come up with a solution to inheriting from `Linq<T>` and `LinqExtended<T>` without having to override a significant number of methods anyhow. However, this would mean you'd have to make further changes to both `Linq<T>` and `LinqExtended<T>` to support the pattern described in [Extending.spec.ts](https://github.com/OpenXmlDev/linq-to-xml/blob/main/packages/linq-to-xml/test/Extending.spec.ts).

For inheriting to make sense, your base classes would have to return instances of more derived classes. Therefore, on the most abstract level, the pattern looks like this:

In the "first layer", you'd turn your current `Linq<T>` into an abstract base class that only offers the most basic methods. The following is an excerpt. Note that `create` is a factory method passed to the constructor. This is used in the `filters()` method, for example, to create an instance of a more derived class.

```typescript
abstract class LinqBase<T, TLinq extends LinqBase<T, TLinq>> implements Iterable<T> {
  constructor(
    protected readonly source: Iterable<T>,
    protected readonly create: (source: Iterable<T>) => TLinq
  ) {}

  [Symbol.iterator](): Iterator<T> {
    return this.source[Symbol.iterator]();
  }

  filter(...filters: IterableFilter<T>[]): TLinq {
    return this.filters(filters);
  }

  filters(filters: Iterable<IterableFilter<T>>): TLinq {
    return this.create(applyFilters(this.source, filters));
  }
}
```

For developers wanting to use just that feature set, you would provide the following class and already existing factory method:

```typescript
class Linq<T> extends LinqBase<T, Linq<T>> {
  constructor(source: Iterable<T>) {
    super(source, linq);
  }
}

function linq<T>(source: Iterable<T>): Linq<T> {
  return source instanceof Linq ? source : new Linq(source);
}
```

In the next layer, you would provide additional methods as already done by the current `LinqExtended<T>` class.

```typescript
abstract class LinqExtendedBase<T, TLinq extends LinqExtendedBase<T, TLinq>> extends LinqBase<T, TLinq> {
  //
  // Base class methods that need to be overridden
  //

  override transform<TResult>(
    transform: IterableValueTransform<T, TResult>
  ): LinqExtended<TResult> {
    return linqExtended(transform(this.source));
  }

  //
  // Additional methods
  //

  skip(count: number): TLinq {
    return this.create(skip<T>(count)(this.source));
  }

  take(count: number): TLinq {
    return this.create(take<T>(count)(this.source));
  }

  select<TResult>(
    selector: SelectorWithIndex<T, TResult>
  ): LinqExtended<TResult> {
    return this.transform(select(selector));
  }

  first(predicate?: PredicateWithIndex<T>): T {
    return first(this.filterSequence(predicate));
  }

  firstOrDefault(predicate?: PredicateWithIndex<T>): T | null {
    return firstOrDefault<T>()(this.filterSequence(predicate)) ?? null;
  }

  //
  // Helper methods
  //

  protected filterSequence(predicate?: PredicateWithIndex<T>): Iterable<T> {
    return predicate ? where(predicate)(this.source) : this.source;
  }
}

/**
 * This is a concrete subclass that provides exactly the methods of its parent.
 */
class LinqExtended<T> extends LinqExtendedBase<T, LinqExtended<T>> {
  constructor(source: Iterable<T>) {
    super(source, linqExtended);
  }
}

function linqExtended<T>(source: Iterable<T>): LinqExtended<T> {
  return source instanceof LinqExtended ? source : new LinqExtended(source);
}
```

If I (or other developers of course) then wanted to provide even more methods, I would add a third layer as follows:

```typescript
class LinqIterable<T> extends LinqExtendedBase<T, LinqIterable<T>> {
  constructor(source: Iterable<T>) {
    super(source, linqIterable);
  }

  //
  // Base class methods that need to be overridden
  //

  override transform<TResult>(
    transform: IterableValueTransform<T, TResult>
  ): LinqIterable<TResult> {
    return linqIterable(transform(this.source));
  }

  override select<TResult>(
    selector: SelectorWithIndex<T, TResult>
  ): LinqIterable<TResult> {
    return this.transform(select(selector));
  }

  //
  // Additional methods
  //

  single(predicate?: PredicateWithIndex<T>): T {
    return single(this.filterSequence(predicate));
  }

  singleOrDefault(predicate?: PredicateWithIndex<T>): T | null {
    return singleOrDefault<T>()(this.filterSequence(predicate)) ?? null;
  }
}

function linqIterable<T>(source: Iterable<T>): LinqIterable<T> {
  return source instanceof LinqIterable ? source : new LinqIterable(source);
}
```

At the moment, only the transformations would have to be overridden. I struggled with adding a generic factory method for arbitrary element types (the TypeScript compiler complained). Maybe you have an idea how we might even avoid having to override the transformations. However, this would already be a big improvement.

The unit tests that you will see establish that this works as intended:

```typescript
test('LinqExtendedBase methods return instances of LinqIterable', () => {
  const sequence: LinqIterable<number> = linqIterable([1, 2, 3, 4, 5]);

  // Use the skip() and take() methods implemented by LinqExtendedBase<T, TLinq>
  // to filter the sequence. Note that filteredSequence is an instance of
  // LinqIterable<T>!
  const filteredSequence = sequence.skip(2).take(1);
  expect(filteredSequence).toBeInstanceOf(LinqIterable);

  // Use a resolution implemented by LinqIterable<T> to resolve a value.
  const resolution = filteredSequence.single();
  expect(resolution).toBe(3);
});

test('LinqBase methods return instances of LinqIterable', () => {
  const sequence: LinqIterable<number> = linqIterable([1, 2, 3, 4, 5]);

  // Use the filter() method implemented by LinqBase<T, TLinq> to filter the
  // sequence. Note that filteredSequence is an instance of LinqIterable<T>!
  const filteredSequence = sequence.filter(skip(2), take(1));
  expect(filteredSequence).toBeInstanceOf(LinqIterable);

  // Use a resolution implemented by LinqIterable<T> to resolve a value.
  const resolution = filteredSequence.single();
  expect(resolution).toBe(3);
});
``` 

What do you think?

**Comment by electricessence** [comment] 2022-01-29 17:11
Ok this is awesome.  I was trying to unravel how to properly make that work in my brain.  I would love to implement.
I'll spend some time on it today. :)

**Comment by ThomasBarnekow** [comment] 2022-01-29 17:15
Thanks! Please have a look at the code in Extending.spec.ts. There are more comments than in the comment above (which I shortened a bit).

Further, do you have an idea on how to also avoid having to override the transformations? Adding a generic method did not work for me.

**Comment by electricessence** [comment] 2022-01-29 17:21
Ok so... Here's the problem..  I always run into this and it really sucks.
Generics don't translate in this pattern that you've presented.  I actually tried this exact thing last night and failed.  I then started writing you and realized I should just wait and think about it.

Consider this problem with `TLinq`...
The results from different methods might be `TLinq<T>` or `TLinq<TResult>` or `TLinq<TSelect>`.  As far as I know and researched, there is no way to define a generic that allows for a generic itself.

Do you have an email or some other way we can communicate, we might be able to collaborate better.

**Comment by electricessence** [comment] 2022-01-29 17:26
Another pattern that can work is extension of properties.
Instead of individual methods (that most devs are familiar with) you can add a member that contains all the extensions related.
Like `.xml` which contains all the specific XML methods... But that seems to always loop back to needing to override the entire class.

I wish there was a way.  But this is one of the reasons the lib has ended up where it is.
I'm optimistic, let's keep thinking.

**Comment by electricessence** [comment] 2022-01-29 17:27
I'm gonna keep tinkering.

**Comment by electricessence** [comment] 2022-01-29 21:14
OK!  DONE!
https://github.com/tsdotnet/linq/releases/tag/v1.2.0
https://www.npmjs.com/package/@tsdotnet/linq

Lemme know if you run into any issues.
But I think this is what you needed and even more.
I migrated everything that made sense to implement in the base classes that didn't collide with the generic type.

Also added `.single` and `.singleOrDefault`. 😄

**Comment by electricessence** [comment] 2022-01-29 21:16
So the idea is that `Linq<T>` is light-weight and doesn't take anything on that makes assumptions about what a dev/consumer wants.
`LinqExtended<T>` assumes you want a lot more and provides the common resolutions that you might expect.
It think this was a strong step in the right direction.
Thanks for your encouragement.

**Comment by electricessence** [comment] 2022-01-29 21:33
> Further, do you have an idea on how to also avoid having to override the transformations? Adding a generic method did not work for me.

I did my best with this update.  There are limitations, but this should simplify your work quite a bit.

**Comment by ThomasBarnekow** [comment] 2022-01-30 11:00
Hi @electricessence, I am having a look as I write this. If you've run into issues, it seems you've not correctly implemented the pattern. And by changing the names of the filter methods (e.,g., renamed multi-param `filter` into `filterWith`), you introduced breaking API changes. Thereby, you provided the best explanation of why I wanted to be careful from taking a dependency on something that might change my public API. I don't know whether you are using semantic versioning, but at least in the .NET world, this should have been a new major version.

**Comment by electricessence** [comment] 2022-01-30 14:33
Yes.  This is a breaking change, but for a lesser use case.   IMO, a minor version is enough.
`filter` is not renamed but retooled to avoid creating an array for every use.  Memory efficiency is important to me, and although convenient `(...params)` in TypeScript transpiles down to an array that is a copy of attributes.  

Having a filter method that takes multiple filters is nice and simple from an API perspective, but recently because of my work in .NET I have a hard time justifying it for every use case.  Hence separating the `.filter` single-param (more common, if not really used much) from the `.filterWith` multi-param (which is not likely used as much as the single-param) is a necessary shift.  In .NET you could via overloading mark a method as `[Obsolete]` (deprecated) and proceed, but because TypeScript overloads do not operate in the same way, this is not possible.

So in the end, the change was made as a memory/performance optimization.

**Comment by electricessence** [comment] 2022-01-30 14:39
As for future changes, I never thought to make any, but your work has helped me see a better way for these classes in order to enable developers like you to extend from `LinqBase<T>` and `LinqResolverBase<T>` and save time and effort.
I've put a lot of thought into what should be done.  I don't expect more unless it's a non-breaking change that can help facilitate your efforts.

**Comment by ThomasBarnekow** [comment] 2022-02-01 11:31
Hi @electricessence, I think we can close this issue now. Thanks for the discussion, which helped both of us evolve our respective libraries.

**Closed as completed by ThomasBarnekow** 2022-02-01 11:31 UTC

**Comment by electricessence** [comment] 2022-02-01 15:14
Yes!  THANK YOU!  I really appreciate the discourse. :)
Thank you for asserting what you needed/wanted. :)
If you think of anything else, don't hesitate to create an issue on the repo orr make a PR. :)
